# NUMPY- NUMerical PYthon

In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [6]:
a=np.array([1,2,3])

In [7]:
a


array([1, 2, 3])

In [9]:
#to find the no. of elements in array
a.size


3

In [11]:
#multidimensional data in arrays
b=np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [13]:
#to know the shape of an array
b.shape

(2, 2)

In [15]:
#to know the no.of dimensions
b.ndim

2

In [18]:
#to reshape the data 
b.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [19]:
#to know the data type in an array
b.dtype

dtype('int32')

In [21]:
#to find the min and max values in an array
b.min()


1

In [22]:
b.max()

4

In [25]:
#arange function
b=np.arange(20)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
b.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [30]:
c=np.arange(18).reshape(3,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [31]:
#ravel function-transforms matrix into list
c.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [36]:
#zeroes or ones matrix
np.zeros([2,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
# arange functions like range in list 
b=np.arange(2,12,3)
b

array([ 2,  5,  8, 11])

In [70]:
c=np.array([5,7,9,12],dtype=float)
c

array([ 5.,  7.,  9., 12.])

In [44]:
#broadcasting arrays= add or sub in matrices
b+c

array([ 7, 12, 17, 23])

In [45]:
b-c

array([-3, -2, -1, -1])

In [59]:
np.random.random([2,4])

array([[0.56307079, 0.03120291, 0.43672393, 0.17851771],
       [0.28611194, 0.39923695, 0.93294361, 0.70496124]])

In [49]:
b*2

array([ 4, 10, 16, 22])

In [50]:
b**2

array([  4,  25,  64, 121], dtype=int32)

# universal functions


In [72]:
#INDEXING

b[2]

8

In [75]:
#SLICING of data
b[1:3]

array([5, 8])

In [78]:
#use of np.nan- used to fill the values whch are not known as nan
np.array([[1,3,5,np.nan],[5,8,np.nan,88]])

array([[ 1.,  3.,  5., nan],
       [ 5.,  8., nan, 88.]])

In [82]:
#rand is upgraded version of random
np.random.rand(2,4)

array([[0.22094522, 0.3494209 , 0.95522932, 0.56647497],
       [0.85774538, 0.6331973 , 0.45308594, 0.78627269]])

In [83]:
#randn can put negative values also
np.random.randn(3,6)

array([[-1.87711169,  0.78267442, -1.03535068, -1.03885406, -0.35908392,
         0.17393257],
       [-0.3065654 ,  0.65119639,  0.63880059, -0.10043132,  0.42054378,
        -1.22359699],
       [-1.91291022,  1.65455441,  0.77933558,  0.6169116 ,  0.27788167,
        -0.03442249]])